CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT, last_seen INTEGER);
CREATE TABLE IF NOT EXISTS msgs (id INTEGER PRIMARY KEY AUTOINCREMENT, to_id TEXT NOT NULL, from_id TEXT NOT NULL, type TEXT NOT NULL, payload TEXT, ts INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_msgs_to ON msgs(to_id, id);
CREATE INDEX IF NOT EXISTS idx_msgs_ts ON msgs(ts);
